### PR TITLE
Upgrade to latest versions of libraries

### PR DESCRIPTION
**Pull request by jeffmay**
## Type of change

- [x] Library upgrade

### CODE REVIEW

**Review by paul-a-kennedy-rally — DISMISSED** [review]
LGTM

**Review by russellremple — DISMISSED** [review]
lgtm

**Review by russellremple — APPROVED** [review]
lgtm (still)

**Review by mingy711 — APPROVED** [review]

**Review by paul-a-kennedy-rally — APPROVED** [review]
LGTM

**Pull request merged**
